### ISSUE TITLE
css vendor problem

### ISSUE THREAD

**Issue by peterchealse** [markshapiro/webpack-merge-and-include-globally#3]
I have the following config:
`
new MergeIntoSingleFilePlugin({
      files: {
        "combined.js": [
          'static/lib/js/jquery.min.js',
          'static/lib/js/bootbox.min.js',
          'static/lib/js/bootstrap.min.js',
          'static/lib/js/d3.v3.min.js',
          'static/lib/js/topojson.v1.min.js',
          'static/lib/js/next-src.js',
          'static/lib/js/snap.svg-min.js'
        ],
        "combined.css": [
          "static/styles/bootstrap.min.css",
          "static/styles/next.css",
          "static/styles/font-awesome.min.css",
          "static/styles/bootstrap-datepicker.min.css",
          "static/styles/bootstrap-datetimepicker.min.css",
          "static/styles/nifty.min.css"
        ],
      },
      transform:{
        'combined.js': code => require("uglify-js").minify(code).code,
        'combined.css': code => require("uglify-js").minify(code).code
      }
    }),
`

I have the js file is combined successfully, but the css failed with the following error:

`
return content.length;
                                  ^
TypeError: Cannot read property 'length' of undefined
at Object.size (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:42:35)
    at obj.assets.compilationAssets.map.asset (/Users/peter/Project/SmartControl-FE/node_modules/webpack/lib/Stats.js:271:38)
    at Array.map (native)
    at Stats.toJson (/Users/peter/Project/SmartControl-FE/node_modules/webpack/lib/Stats.js:268:35)
    at Compiler.<anonymous> (/Users/peter/Project/SmartControl-FE/node_modules/html-webpack-plugin/index.js:68:44)
    at next (/Users/peter/Project/SmartControl-FE/node_modules/tapable/lib/Tapable.js:186:14)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:47:19)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:14:7)
    at mergeFiles (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:9:31)
    at fs.readFile (/Users/peter/Project/SmartControl-FE/node_modules/webpack-merge-and-include-globally/index.js:12:5)
`

**Comment by markshapiro** [comment]
you are trying to minify css code with js minifier library, can you use `clean-css`

**Comment by peterchealse** [comment]
oh..my fault... thanks!
